# Generated by Django 4.2.13 on 2026-04-30 10:56

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_logins', models.PositiveSmallIntegerField(default=0)),
                ('is_mfa_enabled', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dlms_users',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('UPLOAD', 'Uploaded'), ('EDIT', 'Edited'), ('DELETE', 'Deleted'), ('SHARE', 'Shared'), ('PRINT', 'Printed'), ('EXPORT', 'Exported')], max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'dlms_access_logs',
            },
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('classification', models.CharField(choices=[('L1', 'General'), ('L2', 'Internal'), ('L3', 'Confidential')], default='L1', max_length=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('QUARANTINE', 'Quarantined'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=12)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dlms_data_assets',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dlms_departments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('DRIVER', 'Driver'), ('GUEST', 'Guest')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, help_text='JSON map of resource → [read, write, delete] flags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dlms_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_code', models.CharField(default=accounts.models.generate_uuid, max_length=20, unique=True)),
                ('alert_type', models.CharField(choices=[('BULK_DOWNLOAD', 'Bulk Download'), ('OFF_HOURS_ACCESS', 'Off-Hours Access'), ('IMPOSSIBLE_TRAVEL', 'Impossible Travel'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('REPEATED_FAILURE', 'Repeated Auth Failure'), ('DATA_EXFILTRATION', 'Suspected Data Exfiltration'), ('CLASSIFICATION_BREACH', 'Classification Breach'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('raw_evidence', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(default=0.0)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accounts.dataasset')),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accounts.accesslog')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_threat_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dataasset',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN', 'User Login'), ('AUTH_LOGOUT', 'User Logout'), ('AUTH_FAIL', 'Failed Login'), ('AUTH_PASSWORD', 'Password Change'), ('AUTH_MFA', 'MFA Event'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_SUSPEND', 'User Suspended'), ('USER_DELETE', 'User Deleted'), ('ROLE_ASSIGN', 'Role Assigned'), ('DATA_CREATE', 'Asset Created'), ('DATA_READ', 'Asset Accessed'), ('DATA_UPDATE', 'Asset Updated'), ('DATA_DELETE', 'Asset Deleted'), ('DATA_CLASSIFY', 'Asset Reclassified'), ('ALERT_RAISED', 'Alert Raised'), ('ALERT_RESOLVED', 'Alert Resolved'), ('ALERT_ESCALATED', 'Alert Escalated'), ('SYS_CONFIG', 'Config Changed'), ('SYS_EXPORT', 'Report Exported'), ('SYS_BACKUP', 'Backup Triggered')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.threatalert')),
                ('data_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.dataasset')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_target_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_audit_trail',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='accesslog',
            name='data_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='accounts.dataasset'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='threatalert',
            index=models.Index(fields=['severity', 'status'], name='dlms_threat_severit_0b2042_idx'),
        ),
        migrations.AddIndex(
            model_name='threatalert',
            index=models.Index(fields=['triggered_by'], name='dlms_threat_trigger_bcb40d_idx'),
        ),
        migrations.AddIndex(
            model_name='threatalert',
            index=models.Index(fields=['alert_type'], name='dlms_threat_alert_t_15970f_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['classification'], name='dlms_data_a_classif_aa4d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['status'], name='dlms_data_a_status_e61643_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['owner'], name='dlms_data_a_owner_i_aeab81_idx'),
        ),
        migrations.AddIndex(
            model_name='dataasset',
            index=models.Index(fields=['department'], name='dlms_data_a_departm_0b2ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['actor', 'timestamp'], name='dlms_audit__actor_i_ea99d0_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['event_type', 'timestamp'], name='dlms_audit__event_t_e119a3_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', 'timestamp'], name='dlms_access_user_id_7913c3_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['data_asset', 'timestamp'], name='dlms_access_data_as_36b947_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['is_anomalous'], name='dlms_access_is_anom_d661bd_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='dlms_users_role_id_6b8c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department'], name='dlms_users_departm_92dd8d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status'], name='dlms_users_status_8dd83c_idx'),
        ),
    ]
