# Generated by Django 4.2.13 on 2026-04-30 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_types', models.JSONField(default=list, help_text='List of alert_type strings this policy applies to. Empty = all types.')),
                ('min_severity', models.CharField(choices=[('LOW', 'Any severity ≥ Low'), ('MEDIUM', 'Any severity ≥ Medium'), ('HIGH', 'Any severity ≥ High'), ('CRITICAL', 'Critical only')], default='HIGH', max_length=10)),
                ('min_risk_score', models.FloatField(default=7.0, help_text='Policy only fires if alert.risk_score >= this value.')),
                ('action', models.CharField(choices=[('NOTIFY_ADMIN', 'Notify Admin via Email'), ('NOTIFY_ROLES', 'Notify Specific Roles'), ('SUSPEND_USER', 'Suspend Triggering User'), ('QUARANTINE_ASSET', 'Quarantine Related Asset'), ('LOG_ONLY', 'Log Only (no action)')], max_length=20)),
                ('notify_roles', models.JSONField(default=list, help_text='Role names to email when action=NOTIFY_ROLES.')),
                ('escalate_after_minutes', models.PositiveIntegerField(default=60, help_text='If alert is still OPEN after N minutes, escalate severity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alert Policies',
                'db_table': 'dlms_alert_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('SYSTEM', 'In-System Notification')], default='EMAIL', max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('error_msg', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.threatalert')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alerts.alertpolicy')),
            ],
            options={
                'db_table': 'dlms_alert_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.threatalert')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_alert_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
