# Generated by Django 4.2.13 on 2026-04-30 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('L1', 'General'), ('L2', 'Internal'), ('L3', 'Confidential')], max_length=2)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower = evaluated first. Rules with same priority are OR-ed.')),
                ('keywords', models.JSONField(default=list, help_text='Case-insensitive substrings to search in filename + content.')),
                ('regex_pattern', models.CharField(blank=True, help_text='Python-compatible regex. Matched against full text content.', max_length=512)),
                ('file_extensions', models.JSONField(default=list, help_text="e.g. ['xlsx','pdf'] — match by file extension alone.")),
                ('mime_types', models.JSONField(default=list, help_text="e.g. ['application/pdf'] — match by MIME type.")),
                ('is_active', models.BooleanField(default=True)),
                ('auto_encrypt', models.BooleanField(default=False, help_text='If true, assets matched by this rule are flagged for encryption.')),
                ('notify_admin', models.BooleanField(default=False, help_text='If true, a ThreatAlert is raised when this rule fires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_classification_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('UPLOAD', 'On Upload'), ('MANUAL', 'Manual Override'), ('SCHEDULED', 'Scheduled Scan'), ('POLICY', 'Policy Change')], default='UPLOAD', max_length=12)),
                ('level_before', models.CharField(blank=True, max_length=2)),
                ('level_after', models.CharField(max_length=2)),
                ('confidence', models.FloatField(default=1.0, help_text='0.0–1.0 confidence that the classification is correct.')),
                ('matched_terms', models.JSONField(default=list, help_text='Keywords / patterns that caused this classification.')),
                ('scan_notes', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='accounts.dataasset')),
                ('rule_fired', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_classification.classificationrule')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_classification_scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
