# Generated by Django 4.2.13 on 2026-04-30 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('rule_type', models.CharField(choices=[('BULK_DOWNLOAD', 'Bulk Download'), ('OFF_HOURS_ACCESS', 'Off-Hours Access'), ('IMPOSSIBLE_TRAVEL', 'Impossible Travel'), ('REPEATED_AUTH_FAIL', 'Repeated Auth Failure'), ('DATA_EXFILTRATION', 'Data Exfiltration'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('LARGE_UPLOAD', 'Large File Upload'), ('SENSITIVE_PRINT', 'Sensitive Data Print/Export')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold_count', models.PositiveIntegerField(default=10, help_text='Number of events before rule fires (e.g. 10 downloads in window).')),
                ('threshold_window_minutes', models.PositiveIntegerField(default=5, help_text='Sliding window in minutes over which threshold_count is measured.')),
                ('threshold_value', models.FloatField(default=0.0, help_text='Generic numeric threshold (e.g. MB for large upload, km for travel).')),
                ('auto_block', models.BooleanField(default=False, help_text='If true, the triggering user is suspended automatically.')),
                ('notify_roles', models.JSONField(default=list, help_text='List of role names to notify via email on trigger.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dlms_monitoring_rules',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_daily_accesses', models.FloatField(default=0.0)),
                ('avg_download_count', models.FloatField(default=0.0)),
                ('typical_login_hours', models.JSONField(default=list, help_text='List of typical login hours (0-23) based on last 7 days.')),
                ('typical_ips', models.JSONField(default=list, help_text='List of known IP addresses used in last 30 days.')),
                ('typical_locations', models.JSONField(default=list, help_text='City/country strings from GeoIP for known locations.')),
                ('last_known_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_known_location', models.CharField(blank=True, max_length=120)),
                ('risk_baseline', models.FloatField(default=0.0, help_text='Average risk score over the last 7 days.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_user_behavior_profiles',
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detector', models.CharField(choices=[('BULK_DOWNLOAD', 'Bulk Download Detector'), ('OFF_HOURS', 'Off-Hours Access Detector'), ('IMPOSSIBLE_TRAVEL', 'Impossible Travel Detector'), ('REPEATED_FAIL', 'Repeated Auth Failure Detector'), ('EXFILTRATION', 'Exfiltration Detector'), ('LARGE_UPLOAD', 'Large Upload Detector'), ('RISK_SCORE', 'Risk Score Threshold')], max_length=25)),
                ('risk_score', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('escalated_to_alert', models.BooleanField(default=False)),
                ('alert_id', models.BigIntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('monitoring_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.monitoringrule')),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_events', to='accounts.dataasset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dlms_threat_events',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'detector', 'detected_at'], name='dlms_threat_user_id_a0b7d5_idx'), models.Index(fields=['escalated_to_alert'], name='dlms_threat_escalat_c3f453_idx')],
            },
        ),
    ]
